logging:
    level:
        ROOT: INFO
        com.htecgroup.flightadvisor: DEBUG

server:
    port: 8080
spring:
    profiles:
        active: dev
    devtools:
        restart:
            enabled: true
            additional-exclude: static/**,.h2.server.properties
    jackson:
        serialization:
            indent-output: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:file:./target/h2db/db/flight_advisor;DB_CLOSE_DELAY=-1
        username: sa
        password:
        hikari:
            poolName: Hikari
            auto-commit: false
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                web-allow-others: true
                trace: true
    jpa:
        show-sql: true
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.connection.provider_disables_autocommit: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
        hibernate:
            ddl-auto: validate
    data:
        neo4j:
            uri: bolt://localhost:7687
            username: neo4j
            password: secret


application:
    cors:
        allowed-origins: '*'
        allowed-methods: '*'
        allowed-headers: '*'
        exposed-headers: 'Authorization,Link'
        allow-credentials: true
        max-age: 1800
    security:
        base64-secret: YjM4YTU0NTEzNWVlMTEwZGY4YTMwMzZiZGExZmMzZDkzZGM3Y2UwYWQ3MGQwMTc4Y2Q1MjM1NThkZGQzNzY1MGQ3OWEzMGI3ZjUzMDRlMjA0MzEyNWE1NzNkNDRlMWFiNDIzYTg2ZTI5NjFiZDE0NjI2MTUyYzQzODBlYzk2NWY=
        token-validity-in-seconds: 86400
    upload-directory: data
