spring:
    application:
        name: flight-advisor
    profiles:
        active: @spring.profiles.active@
    jmx:
        enabled: false
    data:
        jpa:
            repositories:
                bootstrap-mode: deferred
    jpa:
        open-in-view: false
        properties:
            hibernate.jdbc.time_zone: UTC
            hibernate.id.new_generator_mappings: true
            hibernate.connection.provider_disables_autocommit: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            # modify batch size as necessary
            hibernate.jdbc.batch_size: 25
            hibernate.order_inserts: true
            hibernate.order_updates: true
            hibernate.query.fail_on_pagination_over_collection_fetch: true
            hibernate.query.in_clause_parameter_padding: true
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    messages:
        basename: i18n/messages
    main:
        allow-bean-definition-overriding: true
    jackson:
        default-property-inclusion: non_null
    batch:
        job:
            enabled: false
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
    flyway:
        enabled: true
        baseline-on-migrate: true
